### PR TITLE
Detect link to class (where object is intended)

### LINKED ISSUE #154: Apidoc creates a broken link if only object exists, but $ is missing
For objects without a "companion class" apidoc does not fail if the ending `$` is missing and creates a link to the non-existent regular class API docs page.

The problem is that the class exists in byte code and can't be easily distinguished from cases where both class and object exist in source code.

### PR DESCRIPTION
**Pull request by ennru**
Fixes #154

### CODE REVIEW

**Comment by ennru** [comment]
Only checking for static-methods only is not enough. Traits and abstract classes need to be allowed to link to.

File: src/main/scala/com/lightbend/paradox/apidoc/ApidocPlugin.scala [hunk 1]
```diff
@@ -50,10 +50,11 @@ object ApidocPlugin extends AutoPlugin {
           val scanner = new ClassGraph()
             .whitelistPackages(apidocRootPackage.value)
             .addClassLoader(classLoader)
+            .enableMethodInfo()
```
Comment (raboof) [inline src/main/scala/com/lightbend/paradox/apidoc/ApidocPlugin.scala:53]: I wonder what the impact of this on the running time is - classpath scanning is already a noticable delay in the documentation generation of Akka, does also including method info add to that much?

Comment (ennru) [reply src/main/scala/com/lightbend/paradox/apidoc/ApidocPlugin.scala:53]: For me, it looks like it take 1-2s longer now.
